### ISSUE TITLE
KeyError: 'vit_t'

### ISSUE THREAD

**Issue by realcarlos** [geekyutao/Inpaint-Anything#110]
~/Inpaint-Anything$ bash ./script/remove_anything.sh
2023-10-18 22:10:34.265534: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-18 22:10:34.850371: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Detectron v2 is not installed
Traceback (most recent call last):
  File "remove_anything.py", line 86, in <module>
    masks, _, _ = predict_masks_with_sam(
  File "/home/xxx/Inpaint-Anything/sam_segment.py", line 24, in predict_masks_with_sam
    sam = sam_model_registry[model_type](checkpoint=ckpt_p)
KeyError: 'vit_t'

**Comment by alireza18878** [comment]
@realcarlos Can you please let me know if you found the solution for this issue? I am running into the same issue.

**Comment by nisel1999** [comment]
You can solve this problem by removing “segment_anything” package.

**Comment by fate1997** [comment]
You can install `segment_anything` under this repo instead of the official one
