### ISSUE TITLE
Can't use the "CLICK" and Problem "AttributeError: shape. Did you mean: 'save'?"

### ISSUE THREAD

**Issue by cidxb** [geekyutao/Inpaint-Anything#113]
Hi, new here.

I follow the instruction downloaded all the necessary stuff.
OS:Ubuntu 2204
Environment : python 3.10
And when I use the command as follow :

```
python remove_anything_video.py \
    --input_video ./1.mp4 \
    --coords_type click \
    --point_coords 652 162 \
    --point_labels 1 \
    --dilate_kernel_size 15 \
    --output_dir ./results \
    --sam_model_type "vit_h" \
    --sam_ckpt ./pretrained_models/sam_vit_h_4b8939.pth \
    --lama_config lama/configs/prediction/default.yaml \
    --lama_ckpt ./pretrained_models/big-lama \
    --tracker_ckpt vitb_384_mae_ce_32x4_ep300 \
    --vi_ckpt ./pretrained_models/sttn.pth \
    --mask_idx 2 \
    --fps 25
```
The process will stuck;
More precisely in the script  remove_anything_video.py  line 378  get_clicked_point()
and it is a function from utils.py in line  58

Which after some testing, it is the problem in line 60 to 61
`    cv2.namedWindow("image")
    cv2.imshow("image", img)
`
Seems the whole program will stuck in this line.
But I have tested the cv2.imshow function  separately, it works.
So I wonder if any one has  a explanation of it  ? 
Another  guess is because it cannot read the image from /tmp/ ?

So I change to use the default --coords_type key_in
This time it runs to almost the end, but it comeback with a error in the final stage of storing I think ?
With this :
`Inpainting ...
Traceback (most recent call last):
  File "/home/clark/Projects/Inpaint-Anything-main/remove_anything_video.py", line 393, in <module>
    iio.mimwrite(video_rm_w_mask_p, all_frame_rm_w_mask, fps=fps)
  File "/home/clark/anaconda3/envs/FinRL/lib/python3.10/site-packages/imageio/v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/home/clark/anaconda3/envs/FinRL/lib/python3.10/site-packages/imageio/plugins/pyav.py", line 626, in write
    if any(f.shape != ndimage[0].shape for f in ndimage):
  File "/home/clark/anaconda3/envs/FinRL/lib/python3.10/site-packages/imageio/plugins/pyav.py", line 626, in <genexpr>
    if any(f.shape != ndimage[0].shape for f in ndimage):
  File "/home/clark/anaconda3/envs/FinRL/lib/python3.10/site-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: shape. Did you mean: 'save'?
`

I think it is a dependence  problem? But I am not sure, didn't find anything similar in the issues section...
Hope somebody can help...

**Comment by ert485** [comment]
This looks like the same error I had [due to dependency issues](https://github.com/geekyutao/Inpaint-Anything/issues/161#issuecomment-2292228020). When I followed the installation steps in the readme (in the correct [section](https://github.com/geekyutao/Inpaint-Anything?tab=readme-ov-file#installation-4)), it worked fine. I had python version 3.10
