### ISSUE TITLE
I followed the readme steps and installed successfully. But an error occurred when executing the remove_anything.py file。

### ISSUE THREAD

**Issue by zhaofangtao** [geekyutao/Inpaint-Anything#13]
你好，我这出现一个问题，我按照readme一步步安装成功，最后执行remove_anything.py文件时报错：

Detectron v2 is not installed
Traceback (most recent call last):
  File "D:\AI\Inpaint-Anything\remove_anything.py", line 75, in <module>
    masks, _, _ = predict_masks_with_sam(
  File "D:\AI\Inpaint-Anything\sam_segment.py", line 24, in predict_masks_with_sam
    sam.to(device=device)
  File "C:\Users\xxx\PycharmProjects\pythonProject2\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\xxx\PycharmProjects\pythonProject2\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\xxx\PycharmProjects\pythonProject2\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\xxx\PycharmProjects\pythonProject2\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\xxx\PycharmProjects\pythonProject2\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\xxx\PycharmProjects\pythonProject2\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\xxx\PycharmProjects\pythonProject2\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by RysonFeng** [comment]
你好，原代码中默认是使用cuda设备运行模型，所以当检测不到cuda设备时，即纯cpu运行时，会报错。现已更新相应纯cpu运行的功能，你可以再pull下来运行试试。
另外，如果你的机器本身有nvidia GPU，但是 torch.cuda.is_available() 的输出为 False，可能nvidia driver的版本比较老，导致cuda toolkit 没有正确安装。

**Comment by geekyutao** [comment]
I close this issue as completed.
