### ISSUE TITLE
运行时出现错误

### ISSUE THREAD

**Issue by GYiFeng** [geekyutao/Inpaint-Anything#14]
2023-04-19 14:17:53.241788: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-19 14:17:53.291639: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-19 14:17:54.054049: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "replace_anything.py", line 77, in <module>
    masks, _, _ = predict_masks_with_sam(
  File "/home/Inpaint-Anything/sam_segment.py", line 23, in predict_masks_with_sam
    sam = sam_model_registry[model_type](checkpoint=ckpt_p)
  File "/home/Inpaint-Anything/segment_anything/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "/home/Inpaint-Anything/segment_anything/segment_anything/build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "/opt/miniconda3/envs/Inpainting/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/miniconda3/envs/Inpainting/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/opt/miniconda3/envs/Inpainting/lib/python3.8/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/opt/miniconda3/envs/Inpainting/lib/python3.8/site-packages/torch/serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: PytorchStreamReader failed reading file data/11: invalid header or archive is corrupted

应该如何解决？还有一个问题，那个big-lama是把链接里面两个文件都放在pretrained_models里面吗？

**Comment by AIBUWAN** [comment]
1）可能是你的tensorflow，tensorrt没安装对，如果是在GPU上运行用`conda install tensorflow-gpu`
2）那里面的models和config都要下下来

**Comment by geekyutao** [comment]
I assume the author has fixed the issue and close it.
