### ISSUE TITLE
stable-diffusion-webui-forge error

### ISSUE THREAD

**Issue by navin-hariharan** [geekyutao/Inpaint-Anything#160]
Traceback (most recent call last):
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
response = await route_utils.call_process_api(
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
output = await app.get_blocks().process_api(
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
result = await self.call_function(
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
prediction = await anyio.to_thread.run_sync( # type: ignore
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread
return await future
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\anyio_backends_asyncio.py", line 807, in run
result = context.run(func, *args)
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
response = f(*args, **kwargs)
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-webui-inpaint-anything\ia_threading.py", line 165, in wrapper
res = func(*args, **kwargs)
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-webui-inpaint-anything\ia_threading.py", line 125, in wrapper
res = func(*args, **kwargs)
File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 207, in run_sam
if sam_image["image"].shape == seg_image.shape and np.all(sam_image["image"] == seg_image):
IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices

https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/9cb69baf9fcd0ac2847790555fc8ab603794f1b2

**Comment by jkw117** [comment]
I have the very similar issue - StableDiffusion WebUI Forge: 
Traceback (most recent call last):
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-inpaint-anything\ia_threading.py", line 165, in wrapper
    res = func(*args, **kwargs)
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-inpaint-anything\ia_threading.py", line 125, in wrapper
    res = func(*args, **kwargs)
  File "C:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 208, in run_sam
    if sam_image["image"].shape == seg_image.shape and np.all(sam_image["image"] == seg_image):
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by Bruce20090827** [comment]
Me 2
here is my error log
Traceback (most recent call last):
  File "D:\webui_forge\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\webui_forge\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\webui_forge\system\python\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\webui_forge\system\python\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\webui_forge\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\webui_forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\webui_forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\webui_forge\system\python\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "D:\webui_forge\webui\extensions\sd-webui-inpaint-anything\ia_threading.py", line 125, in wrapper
    res = func(*args, **kwargs)
  File "D:\webui_forge\webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 223, in select_mask
    mask = sam_image["mask"][:, :, 0:1]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
