### ISSUE TITLE
Remove from video, can't switch to different mask 

### ISSUE THREAD

**Issue by ert485** [geekyutao/Inpaint-Anything#161]
I can't seem to change `--mask_idx 2` to `--mask_idx 1` without getting this error `'Image' object has no attribute 'shape'`
It was working fine before I switched that.
```
python remove_anything_video.py \
  --input_video ./example/video/paragliding/original_video.mp4  \
  --coords_type key_in     --point_coords 652 162     --point_labels 1   \
  --dilate_kernel_size 15     --output_dir ./results     --sam_model_type "vit_h"   \
  --sam_ckpt ./pretrained_models/sam_vit_h_4b8939.pth  \
  --lama_config lama/configs/prediction/default.yaml     --lama_ckpt ./pretrained_models/big-lama \
  --tracker_ckpt vitb_384_mae_ce_32x4_ep300     --vi_ckpt ./pretrained_models/sttn.pth   \
  --mask_idx 1     \
  --fps 25

2024-08-15 20:45:59.493785: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-15 20:45:59.513175: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-15 20:45:59.519164: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-15 20:45:59.533569: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-15 20:46:00.407987: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Tracking ...
Segmenting ...
Inpainting ...
Traceback (most recent call last):
  File "/home/ubuntu/Inpaint-Anything/remove_anything_video.py", line 393, in <module>
    iio.mimwrite(video_rm_w_mask_p, all_frame_rm_w_mask, fps=fps)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/imageio/v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/imageio/plugins/pyav.py", line 626, in write
    if any(f.shape != ndimage[0].shape for f in ndimage):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/imageio/plugins/pyav.py", line 626, in <genexpr>
    if any(f.shape != ndimage[0].shape for f in ndimage):
AttributeError: 'Image' object has no attribute 'shape'. Did you mean: 'save'?
```

**Comment by ert485** [comment]
I may have had the wrong python environment active, whoops 🙈. Just need the right versions of all the dependencies

**Comment by ert485** [comment]
Also, in my experience mask index 1 is usually better (very much true in this case), but the readme suggests mask index 2 is usually better.
