### ISSUE TITLE
 Please help with the version number of python you are using

### ISSUE THREAD

**Issue by dilong9595** [geekyutao/Inpaint-Anything#43]
Please help with the version number of python you are using.      My installation with python=3.10.6 always fails

**Comment by geekyutao** [comment]
I use 3.8.5.

**Comment by gql666** [comment]
can python3.11 run the program?i failed when trying it

**Comment by gql666** [comment]
Always have a error when i try to install the list

**Comment by geekyutao** [comment]
> 

Not sure about this. Downgrade python to 3.10 or 3.8 if convenient.

**Comment by steinhaug** [comment]
Google Colab seems impossible for this then, been at ut for some hours now. Its either problems here:

`/content/Inpaint-Anything
Traceback (most recent call last):
  File "/content/Inpaint-Anything/remove_anything.py", line 9, in <module>
    from lama_inpaint import inpaint_img_with_lama
  File "/content/Inpaint-Anything/lama_inpaint.py", line 19, in <module>
    from saicinpainting.evaluation.utils import move_to_device
  File "/content/Inpaint-Anything/lama/saicinpainting/evaluation/__init__.py", line 6, in <module>
    from saicinpainting.evaluation.losses.base_loss import SSIMScore, LPIPSScore, FIDScore
  File "/content/Inpaint-Anything/lama/saicinpainting/evaluation/losses/base_loss.py", line 15, in <module>
    from .lpips import PerceptualLoss
  File "/content/Inpaint-Anything/lama/saicinpainting/evaluation/losses/lpips.py", line 15, in <module>
    from saicinpainting.utils import get_shape
  File "/content/Inpaint-Anything/lama/saicinpainting/utils.py", line 12, in <module>
    from pytorch_lightning import seed_everything
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 28, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/metrics/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.functional.accuracy import _accuracy_compute, _accuracy_update
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/metrics/functional/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.functional.accuracy import accuracy  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/metrics/functional/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.classification.helpers import _input_format_classification, DataType
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/metrics/classification/helpers.py", line 19, in <module>
    from pytorch_lightning.metrics.utils import select_topk, to_onehot
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/metrics/utils.py", line 18, in <module>
    from pytorch_lightning.utilities import rank_zero_warn
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from torchtext.legacy.data import Batch
ModuleNotFoundError: No module named 'torchtext.legacy'`

But it's guranteed fail in the lama :
`Run inpainting
Traceback (most recent call last):
  File "/content/lama/bin/predict.py", line 32, in <module>
    from saicinpainting.training.trainers import load_checkpoint
  File "/content/lama/saicinpainting/training/trainers/__init__.py", line 3, in <module>
    from saicinpainting.training.trainers.default import DefaultInpaintingTrainingModule
  File "/content/lama/saicinpainting/training/trainers/default.py", line 10, in <module>
    from saicinpainting.training.modules.fake_fakes import FakeFakesGenerator
  File "/content/lama/saicinpainting/training/modules/fake_fakes.py", line 2, in <module>
    from kornia import SamplePadding
ImportError: cannot import name 'SamplePadding' from 'kornia' (/usr/local/lib/python3.10/dist-packages/kornia/__init__.py)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-57-0248d407ec6a> in <cell line: 12>()
     10 
     11 plt.rcParams['figure.dpi'] = 200
---> 12 plt.imshow(plt.imread(f"/content/output/{fname.split('.')[1].split('/')[2]}_mask.png"))
     13 _=plt.axis('off')
     14 _=plt.title('inpainting result')

IndexError: list index out of range`

You need getting past the installing problems though. For me the requrements for lama looks solved like this:

first failing:
`ERROR: Failed building wheel for scikit-image
ERROR: No matching distribution found for torch==1.8.0+cu111
ERROR: No matching distribution found for opencv-python-headless==4.1.2.30`

Then theese corrects:
`!pip install --upgrade pip
!pip uninstall --yes --quiet osqp
!pip install -U scikit-survival
!pip install opencv-contrib-python
!pip install opencv-python
!pip install opencv-python-headless
!pip install pytorch-lightning
!pip uninstall kornia
!pip install kornia --no-dependencies
!pip install hydra-core --upgrade
!pip install webdataset`

Im thinking downgrading to Python 3.8 won't cut it, but maby it does.
