### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'sam_vit_h_4b8939.pth'   run error

### ISSUE THREAD

**Issue by kosuke430** [geekyutao/Inpaint-Anything#6]
I am trying to do a Fill any thing and get an execution error like this Please help me with a solution.

Traceback (most recent call last):
  File "fill_anything.py", line 79, in <module>
    masks, _, _ = predict_masks_with_sam(
  File "/home/haga/Inpaint-Anything/sam_segment.py", line 23, in predict_masks_with_sam
    sam = sam_model_registry[model_type](checkpoint=ckpt_p)
  File "/home/haga/Inpaint-Anything/segment_anything/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "/home/haga/Inpaint-Anything/segment_anything/segment_anything/build_sam.py", line 104, in _build_sam
    with open(checkpoint, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sam_vit_h_4b8939.pth'

**Comment by RysonFeng** [comment]
Hi，it seems that model checkpoint of sam does not exist. 
You can first download the model checkpoints provided in [segment_anything](https://github.com/geekyutao/Inpaint-Anything/tree/main/segment_anything) (e.g. [sam_vit_h_4b8939.pth](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth). And then change the args `--sam_ckpt` to the checkpoint path.
