### ISSUE TITLE
Remove Anything Video fails on large files

### ISSUE THREAD

**Issue by duffey** [geekyutao/Inpaint-Anything#65]
Perhaps it is possible to read the stream the video in and out?

```
Traceback (most recent call last):
  File "C:\Users\user\code\Inpaint-Anything\remove_anything_video.py", line 357, in <module>
    all_frame = iio.mimread(video_raw_p)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\v2.py", line 444, in mimread
    raise RuntimeError(
RuntimeError: imageio.mimread() has read over 256000000B of image data.
Stopped to avoid memory problems. Use imageio.get_reader(), increase threshold, or memtest=False
```

**Comment by geekyutao** [comment]
Seems I/O problem. iio may not support such a large video. You can try splitting the video into clips?

**Comment by dragen1860** [comment]
simply add `memtest=False` solved it.

**Comment by duffey** [comment]
Sorry I forgot to close this. Can't confirm whether this works because I lost interest on what I was using this for.
