### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory

### ISSUE THREAD

**Issue by mike-silver-Crafty-Apes-VFX** [geekyutao/Inpaint-Anything#75]
Occurs when running demo command for replace_anything.py

OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/.cache/huggingface/hub/models--stabilityai--stable-diffusion-2-inpainting/snapshots/da570f226126f4586426047b8aa3f767de4eb55d/text_encoder.

2023-06-05 15:04:06.824707: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-05 15:04:07.994878: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/user/replace_anything.py", line 163, in <module>
    img_replaced = replace_img_with_sd(img, mask, args.text_prompt, device=device)
  File "/home/user/stable_diffusion_inpaint.py", line 35, in replace_img_with_sd
    pipe = StableDiffusionInpaintPipeline.from_pretrained(
  File "/home/user/miniconda3/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 1039, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/user/miniconda3/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 445, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/user/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2387, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/.cache/huggingface/hub/models--stabilityai--stable-diffusion-2-inpainting/snapshots/da570f226126f4586426047b8aa3f767de4eb55d/text_encoder.

**Comment by tina10128** [comment]
I updated torch==2.0.0 (1.9.0 can't work)
It's work for me.

I think this project have many library problems, such as opencv, torch, torchtext.
These libraries always conflict.
I hope the author can provide more complete version information.
