### ISSUE TITLE
c10_cuda.dll" or one of its dependencies

### ISSUE THREAD

**Issue by MajorShahjahan** [geekyutao/Inpaint-Anything#84]
Hi, I am trying to run remove anything video. I am geeting this error.

Traceback (most recent call last):
  File "C:\Users\49176\VsCodeProjects\inpaint_anything\Inpaint-Anything\remove_anything_video.py", line 1, in <module>
    import torch
  File "C:\Users\49176\anaconda3\envs\Inpaint-Anything\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\49176\anaconda3\envs\Inpaint-Anything\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

**Comment by geekyutao** [comment]
Hi, make sure you have correctly install torch before run this.
