### ISSUE TITLE
Error loading script: inpaint_anything.py

### ISSUE THREAD

**Issue by sanasigma** [geekyutao/Inpaint-Anything#95]
Error loading script: inpaint_anything.py
Traceback (most recent call last):
  File "E:\stablediffusion\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\stablediffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stablediffusion\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 35, in <module>
    from fast_sam import FastSamAutomaticMaskGenerator, fast_sam_model_registry
  File "E:\stablediffusion\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\fast_sam\__init__.py", line 1, in <module>
    from .fast_sam_wrapper import FastSAM
  File "E:\stablediffusion\stable-diffusion-webui\extensions\sd-webui-inpaint-anything\fast_sam\fast_sam_wrapper.py", line 5, in <module>
    from ultralytics import YOLO
ModuleNotFoundError: No module named 'ultralytics'

**Comment by geekyutao** [comment]
Hi, I don't think this is caused by Inpaint-Anything repo. Seems like you are using SD-webui.
