### ISSUE TITLE
ValueError: could not broadcast input array from shape (512,512,3) into shape (448,512,3)

### ISSUE THREAD

**Issue by tianshuai** [geekyutao/Inpaint-Anything#96]
在执行`fill_anything.py`这个脚本时报了以下错误：
```
  File "/opt/project/Inpaint-Anything/fill_anything.py", line 135, in <module>
    img_filled = fill_img_with_sd(
  File "/opt/project/Inpaint-Anything/stable_diffusion_inpaint.py", line 32, in fill_img_with_sd
    img_filled = crop_for_filling_post(img, mask, np.array(img_crop_filled))
  File "/opt/project/Inpaint-Anything/utils/mask_processing.py", line 116, in crop_for_filling_post
    image[crop_y:crop_y + crop_size, crop_x:crop_x + crop_size] = filled_image
ValueError: could not broadcast input array from shape (512,512,3) into shape (448,512,3)
```
但是如果坐标参数（--point_coords）换了非主体所在位置就会解决，具体是哪里出了问题？

**Comment by geekyutao** [comment]
Not quite understand your question. Were you using click prompt?

**Comment by chaendizzle** [comment]
I also ran into this issue.

Command:
```
(inpaint-anything) C:\Users\user\InpaintAnything>python fill_anything.py --input_img ./input/wearinghat.png --coords_type key_in --point_coords 373 731 --point_labels 1 --text_prompt "minecraft steve with arms outstretched" --dilate_kernel_size 50 --output_dir ./results --sam_model_type "vit_h" --sam_ckpt ./pretrained_models/sam_vit_h_4b8939.pth

vae\diffusion_pytorch_model.safetensors not found
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.45it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:15<00:00,  3.21it/s]
vae\diffusion_pytorch_model.safetensors not found
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.23it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:15<00:00,  3.19it/s]
vae\diffusion_pytorch_model.safetensors not found
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.27it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:15<00:00,  3.18it/s]

Traceback (most recent call last):
  File "fill_anything.py", line 135, in <module>
    img_filled = fill_img_with_sd(
  File "C:\Users\user\InpaintAnything\stable_diffusion_inpaint.py", line 31, in fill_img_with_sd
    img_filled = crop_for_filling_post(img, mask, np.array(img_crop_filled))
  File "C:\Users\user\InpaintAnything\utils\mask_processing.py", line 116, in crop_for_filling_post
    image[crop_y:crop_y + crop_size, crop_x:crop_x + crop_size] = filled_image
ValueError: could not broadcast input array from shape (512,512,3) into shape (486,512,3)
```

The issue appears to be that `image[crop_y:crop_y + crop_size, crop_x:crop_x + crop_size]` can be smaller than `crop_size x crop_size` when it goes off the edge of the image. To resolve this, I replaced:
```
# Fill the image
image[crop_y:crop_y + crop_size, crop_x:crop_x + crop_size] = filled_image
```
with
```
# Fill the image
dst_shape = image[crop_y:crop_y + crop_size, crop_x:crop_x + crop_size].shape
if filled_image.shape != dst_shape:
    filled_image = np.asarray(Image.fromarray(filled_image).resize(tuple(reversed(dst_shape[:2])), Image.Resampling.LANCZOS))
image[crop_y:crop_y + crop_size, crop_x:crop_x + crop_size] = filled_image
```
and it succeeded.
